content:
  - name: blog
    label: Blog
    path: src/content/blog
    type: collection
    view:
      fields: [ title, pubDatetime ]
    fields:
    - name: pubDatetime
      label: Publish Date
      type: date
    - name: modDatetime
      label: Modified Date
      type: date
    - name: title
      label: Title
      type: string
    - name: body
      label: Body
      type: rich-text
    