content:
  - name: blog
    label: Blog
    path: src/content/blog
    type: collection
    fields:
    - name: pubDatetime
      type: date
    - name: modDatetime
      type: date
    - name: title
      type: string
    - name: body
      type: rich-text
    