content:
  - name: blog
    label: Blog
    path: src/content/blog
    type: collection
    view:
      fields: [ title, pubDatetime, featured ]
    fields:
    - name: pubDatetime
      label: Publish Date
      type: date
    - name: modDatetime
      label: Modified Date
      type: date
    - name: title
      label: Title
      type: string
    - name: featured
      label: Featured
      type: boolean
    - name: draft
      label: Draft
      type: boolean
      default: true
    - name: tags
      label: Tags
      type: string
      list: true
    - name: description
      label: Description
      type: text
    - name: type
      label: Type
      type: select
      options:
        values: [ fragment, loadout, note, project, source, theme ]
    - name: body
      label: Body
      type: rich-text
    - name: aiUsage
      label: AI Usage
      type: select
      options:
        values: [ none, research, proofreading, editing, code-assistance,  ]
        multiple: true
    