name: Create Fragment Issue

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Title of the issue'
        required: true
        default: 'New Fragment Note'
      body:
        description: 'Description of the issue'
        required: true
        default: 'Details of the digital garden note fragment.'
      labels:
        description: 'Labels for the issue'
        required: false
        default: 'fragment'

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        uses: actions/github-script@v6
        with:
          script: |
            const { github, context } = require('@actions/github');
            const title = '${{ inputs.title }}';
            const body = '${{ inputs.body }}';
            const labels = '${{ inputs.labels }}'.split(',');

            await github.issues.create({
              ...context.repo,
              title,
              body,
              labels,
            });