name: Create Fragment Issue

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Title of the issue'
        required: true
        default: 'New Fragment Note'
      body:
        description: 'Description of the issue'
        required: true
        default: 'Details of the digital garden note fragment.'
      labels:
        description: 'Labels for the issue'
        required: false
        default: 'fragment'

# Add the permissions section here
permissions:
  issues: write

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        uses: actions/github-script@v6
        env:
          ISSUE_TITLE: ${{ inputs.title }}
          ISSUE_BODY: ${{ inputs.body }}
          ISSUE_LABELS: ${{ inputs.labels }}
        with:
          script: |
            const title = process.env.ISSUE_TITLE;
            const body = process.env.ISSUE_BODY;
            const labels = process.env.ISSUE_LABELS ? process.env.ISSUE_LABELS.split(',') : [];

            await github.rest.issues.create({
              ...context.repo,
              title,
              body,
              labels,
            });