name: Set Dates

on:
  push:
    branches:
      - main

jobs:
  set-dates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update dates in Markdown files
        run: |
          git fetch --prune --unshallow

          # Update modDatetime for modified files
          git diff --cached --name-status | grep -i '^M.*\.md$' | grep -E '^(src/content/(blog|projects)/)' | while read _ file; do
            filecontent=$(cat "$file")
            frontmatter=$(echo "$filecontent" | awk -v RS='---' 'NR==2{print}')
            draft=$(echo "$frontmatter" | awk '/^draft: /{print $2}')
            if [ "$draft" = "false" ]; then
              echo "$file modDateTime updated"
              sed -i "/---.*/,/---.*/s/^modDatetime:.*$/modDatetime: $(date -u "+%Y-%m-%dT%H:%M:%SZ")/" "$file"
              git add "$file"
            fi
          done

          # Add pubDatetime and modDatetime for new files
          git diff --cached --name-status | egrep -i "^(A).*\.(md|mdx)$" | grep -E '^(src/content/(blog|projects)/)' | while read a b; do
            echo "Adding timestamps for $b"
            sed -i "/---/a pubDatetime: $(date -u "+%Y-%m-%dT%H:%M:%SZ")\nmodDatetime: $(date -u "+%Y-%m-%dT%H:%M:%SZ")" "$b"
            git add "$b"
          done

      - name: Commit changes
        run: |
          git config --local user.email "daniel@rokkit200.co"
          git config --local user.name "Daniel van der Merwe"
           git add .
          if ! git diff --cached --quiet; then
            git commit -m "Update dates"
            git push
          else
            echo "No changes to commit."
          fi
